### ISSUE TITLE
Voting results

### ISSUE THREAD

**Issue by l-heimann** [bufak-wiwi/konfetti#15] opened 2023-09-23 13:42 UTC
- Display of all open and closed votes
- For open votes: Show number of votes cast
- For closed votes: Display of the result

**Comment by fullbeats** [comment] 2023-10-24 14:40
Duplicate of #9 ?

**Comment by l-heimann** [comment] 2023-10-24 14:51
#9 describes voting functionality for users, this issue describes view of voting results for admins (for presentation in plenary sessions)

**Closed as completed** 2024-11-16 11:08 UTC
Labels: admin
